services:
  # Backend Service (FastAPI/Python)
  - type: web
    name: backend
    env: docker
    # The directory context for the build
    dockerContext: ./backend
    # The path to the Dockerfile
    dockerfilePath: ./backend/Dockerfile
    # Set the plan (e.g., free, starter)
    plan: free
    # Health check to ensure the service is running
    healthCheck:
      path: /
      port: 8000
    # Make this service private so it's not directly accessible from the internet
    # It will be accessed via the frontend's rewrite rule
    private: true

  # Frontend Service (React/Node.js)
  - type: web
    name: frontend
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    # Health check for the frontend server
    healthCheck:
      path: /
      port: 3000
    # Rewrite rule to proxy API requests to the backend
    # Any request to your-frontend-url.onrender.com/api/* will be sent to the backend
    rewrites:
      - source: /api/:path*
        destination: http://backend:8000/:path*
    # Set autoDeploy to true to automatically deploy on pushes to your Git repository
    autoDeploy: false